config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'hotels#index'
  resources :contacts
  resources :hotels, :only => [:index, :show] do
  resources :reviews, :only => [:index, :show, :new, :create]
  resources :reservations, :only=> [:new, :create, :show]

  end
  resources :prefectures, :only => [:index, :show]
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/hotel.rb
class Hotel < ApplicationRecord
	mount_uploader :picture, PictureUploader
	belongs_to :prefecture
	has_many :reservations
	has_many :reviews
end

app/models/prefecture.rb
class Prefecture < ApplicationRecord
	has_many :hotels
end

app/models/reservation.rb
class Reservation < ApplicationRecord
	belongs_to :hotel
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :hotel

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def new
    	@contact = Contact.new
  	end

  	def create
    	@contact = Contact.new(contact_params)
    	if @contact.save
      		redirect_to contact_path(@contact)
    	end
	end

 	def contact_params
    	params.require(:contact).permit(:name, :email, :body)
  	end

	def show
  		@contact = Contact.find(params[:id])
	end

end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
	def index
  		@q = Hotel.ransack(params[:q])
  		@hotels = @q.result(distinct: true)
	end

	
	def show
  		@hotel = Hotel.find(params[:id])
	end
	


	
	

end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
	def index
		 @prefectures = Prefecture.all
 	end

 	def show
  		@prefecture = Prefecture.find(params[:id])
  		@hotels = @prefecture.hotels
	end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

	 def new
    	@hotel = Hotel.find(params[:hotel_id])
  		@reservation = @hotel.reservations.build
  end

  def create
  		@hotel = Hotel.find(params[:hotel_id])
    	@reservation = Reservation.new(reservation_params)
    	if @reservation.save
          redirect_to hotel_reservation_path(@hotel, @reservation)
      end

	end

 	  def reservation_params
    	params.require(:reservation).permit(:name, :email, :start_date, :end_date, :people, :hotel_id)
  	end

    def show
      @hotel = Hotel.find(params[:hotel_id])
      @reservation = Reservation.find(params[:id])
    end
end      

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	

	def index
	  @hotel = Hotel.find(params[:hotel_id])
	  @reviews = @hotel.reviews
	end

	def new
  		@hotel = Hotel.find(params[:hotel_id])
  		@review = @hotel.reviews.build
	end

	def create
  		@hotel = Hotel.find(params[:hotel_id])
  		@review = Review.new(review_params)
  		if @review.save
    		redirect_to hotel_reviews_path(@hotel)
  		end
	end

	def review_params
  		params.require(:review).permit(:name, :title, :body, :rating, :hotel_id)
	end
	

	def show
  		@hotel = Hotel.find(params[:hotel_id])
  		@review = Review.find(params[:id])
	end
	

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/contacts/new.html.erb
<h1>お問い合わせ</h1>

<%= form_with(model: @contact, local: true) do |form| %>
<!-- name -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

   <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_name %>
  </div>
<!-- description -->
  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :contact_description %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/show.html.erb
<h1>お問い合わせありがとうございました</h1>
<p><%= @contact.name %></p>
<p><%= @contact.email %></p>
<p><%= @contact.body %></p>

app/views/hotels/_form.html.erb
<%= form.file_field :picture %>

app/views/hotels/index.html.erb
<h1>ホテルの一覧</h1>

<%= search_form_for @q do |f| %>
	<%= f.label :name_cont %>
	<%= f.search_field :name_cont %>
	<%= f.submit "検索", class: "btn btn-outline-secondary"%>
<% end %>

<% @hotels.each do |hotel| %>
  <p><%= hotel.name %></p>
  <p><%= hotel.description %></p>
  <%= image_tag(hotel.picture_url, width: 600) if hotel.picture.present? %>

	
  	


<% end %>

app/views/hotels/show.html.erb
<h1>ホテルの詳細ページ</h1>
<p><%= @hotel.name %></p>
<p><%= @hotel.description %></p>
<%= image_tag(@hotel.picture_url, width: 600) if @hotel.picture.present? %>



<end>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="container">
  <nav class="navbar navbar-expand-sm navbar-light">
    
    <a class="navbar-brand font-italic" href="/" style="font-size: 30px"><u>Hotel Project</u></a>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#menu">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div id="menu" class="collapse navbar-collapse d-flex justify-content-end">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="/" class="nav-link">トップページ</a></li>
        <li class="nav-item"><a href="/contacts/new" class="nav-link">お問い合わせ</a></li>
      </ul>
    </div>
  </nav>  
    </div>
    </header>
    <%= yield %>
    <footer class="mt-5">
      <p class="text-center text-muted display-5 bg-light">Hotel Project</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/prefectures/index.html.erb
<p>都道府県の一覧</p>
  <% @prefectures.each do |prefecture| %>
  <p><%= prefecture.name %></p>

  <%= link_to '都道府県の詳細', prefecture_path(prefecture) %> |
<% end %>

app/views/prefectures/show.html.erb
<h1>都道府県詳細ページ</h1>
<p><%= @prefecture.name %></p>



<% @hotels.each do |hotel| %>
  <p><%= hotel.name %></p>
  <p><%= hotel.description %></p>
  <%= image_tag(hotel.picture_url, width: 600) if hotel.picture.present? %>
  

<%= link_to '詳細を見る', hotel_path(hotel) %> |
<%= link_to 'レビューを見る', hotel_reviews_path(hotel) %> |

<% end %>

app/views/reservations/_form.html.erb
<h1>予約ページ</h1>
<%= form_with(model: [@hotel, @reservation], local: true) do |form| %>



<!-- name -->
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :reservation_name %>
  </div>

   <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :reservation_name %>
  </div>
<!-- description -->
  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date, id: :reservation_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, id: :reservation_end_date %>
  </div>

  <div class="field">
    <%= form.label :people %>
    <%= form.number_field :people, id: :reservation_people %>
  </div>

  
    <%= form.hidden_field :hotel_id %>
    
  


  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/reservations/new.html.erb
<%= render 'form', reservation: @reservation %>
<%= link_to 'Back', hotel_reservations_path(@hotel) %>

app/views/reservations/show.html.erb
<h1>お問い合わせ有難う御座います。</h1>

<p>
  <strong>Name:</strong>
  <%= @reservation.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @reservation.email %>
</p>

<p>
  <strong>Start_date:</strong>
  <%= @reservation.start_date %>
</p>

<p>
  <strong>End_date:</strong>
  <%= @reservation.end_date %>
</p>

<p>
  <strong>People:</strong>
  <%= @reservation.people %>
</p>


<%= link_to 'Back', hotel_path(@hotel) %> 

app/views/reviews/index.html.erb
<p>レビューの一覧</p>
<% @reviews.each do |review| %>
  <p>
  <%= review.name %>
  <%= review.title %>
  <%= review.body %>
  <%= review.rating %>
  </p>
<% end %>

app/views/reviews/new.html.erb
<h1>Review</h1>

<%= form_with(model: [@hotel, @review], local: true) do |form| %>
 

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

<%= form.hidden_field :hotel_id %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.text_field :rating %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @review.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.hotel_id %>
</p>

<p>
<strong>rating:</strong>
  <%= @review.rating %>
</p>
<%= link_to 'Edit', edit_hotel_review_path(@hotel,@review) %> |
<%= link_to 'Back',  hotel_reviews_path(@hotel) %> |

<%= link_to 'Destroy', hotel_review_path(@hotel, @review), data: { confirm: 'Are you sure?' }, method: :delete %> 